### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by GTC6244**
Quick template for submitting js-sdk bugs / issues .... thoughts, comments?

@debbly , @Adarsh-Kumar28 , @zanedr , @Ansonhkg  ...

### CODE REVIEW

**Comment by glitch003** [comment]
This is awesome!  Thanks for doing this @GTC6244 !!

2 things:

1) Can you add "SDK version" to the list of questions we ask?
2) Can you also add this to the new typescript repo here: https://github.com/LIT-Protocol/js-sdk

**Comment by GTC6244** [comment]
Done & done @glitch003 !

**Comment by DashKash54** [comment]
Hi @GTC6244 I've seen lot of folks reaching out for resolving issues with ACCs. Since this is quite common how about including the ACC Debugger link in the section- "Before reporting, I have already"

- verified the correctness of my access control condition on the [Debugger](https://lit-accs-debugger.vercel.app/), if the issue is regarding access control conditions

If this doesn't seems a fit for this section, how about just adding it as a separate pointer?

Also, just like we're asking them to search for other issues on Github how about asking them to do the same on our Discord channel since it has a plethora of common issues & their resolutions?

**Comment by GTC6244** [comment]
@Adarsh-Kumar28  - great ideas - included!

**Pull request merged**
