### PR TITLE
Feat: Return node core error to user

### PR DESCRIPTION
**Pull request by DashKash54**
# What

- Throw the errors returned by node (lit-core-rs error format). These are the new errors objects returned by the nodes.
- Some error checking is also done on the client side, standardize those errors to be of the same format as the node errors.

# How

- Update the `throwError()` params to match the node errors

**Note:** Have updated the key `message` to `description` in the thrown error to match node error keys.

# Tests

To test that the new node errors are being thrown just match the console logged node errors (node errors are logged on the console as most common error, you may also check individual errors in the returned object) with the ones "thrown".

### CODE REVIEW

**Review by glitch003 — APPROVED** [review]
This looks great @Adarsh-Kumar28 

I think we need to wait to merge this, until deploy this change on the node side, on serrano.  We will probably do this very soon.

**Comment by hwrdtm** [comment]
@Adarsh-Kumar28 is there a corresponding PR on the new SDK side? Or are the changes already merged in there?

cc @glitch003

**Comment by DashKash54** [comment]
> @Adarsh-Kumar28 is there a corresponding PR on the new SDK side? Or are the changes already merged in there?
> 

@hwrdtm No we have to make these changes for the new SDK as well

**Comment by hwrdtm** [comment]
Will be handled in https://github.com/LIT-Protocol/js-sdk/pull/73

**Pull request closed without merging**
