### PR TITLE
Feat: Sign & Send a transaction with PKP

### PR DESCRIPTION
**Pull request by DashKash54**
## GOAL

Create a Lit JS SDK function that signs a transaction using `LitActions.signEcdsa`

## WHAT

Created a function for signing the transaction as described above

## ADDITIONAL

Already merged the PR for the Rust implementation for `LitActions.signEcdsa`

### CODE REVIEW

**Comment by GTC6244** [comment]
Hey @Adarsh-Kumar28  - the test doesn't work, unfortunately;  I believe it's likely the nonce being invalid, since it's hardcoded to "0x01" ;-).     The return value from the SDK should probably be expanded to actually include the transaction to send to send to the chain, rather than just the signature.   This would then include the nonce used when signing - we could ask for it again from the chain, but risk it being incorrect, and getting a failure response from the sendTransaction.   (It would, of course, fail anyway in this case, as the nonce would be already used but we'd get a mismatched signature error prior to even getting to chain -  the wrong failure message!)

Does this make sense?

**Comment by DashKash54** [comment]
> Hey @Adarsh-Kumar28 - the test doesn't work, unfortunately;

@GTC6244 Yeah, the `manual_tests.html` won't work since it the nonce isn't updated. But I've added another function `sendPKPTransaction` that sends the transaction altogether so we don't need to worry about crafting the transaction again.

I'll change the `manual_tests.html` to use that functions instead

**Review by GTC6244 — APPROVED** [review]
@Adarsh-Kumar28 - I switched the network back to default from "serrano" in the instantiation of the client to keep up with current functionality.   Otherwise this looks good.

**Comment by DashKash54** [comment]
> I switched the network back to default from "serrano" in the instantiation of the client to keep up with current functionality. 

@GTC6244  I've added a comment about changing it to serrano for running our test.

**Pull request merged**
